Fix/PN-13394: spaces in templates AAR and AAR_RADDalt
pagopa/pn-templates-engine pull request #22
Opened 2024-12-02 08:30 UTC by fbianchicodermine

## Short description
Fix spaces in templates for IT lang resolves second empty page for PG.

## How to test
Start microservices pn-template-engine and call API (from Postman collection):
- PUT `/templates-engine-private/v1/templates/notification-aar-radd-alt`
- PUT `/templates-engine-private/v1/templates/notification-aar`

2024-12-03 11:03 UTC, SarahDonvito approved these changes

2024-12-03 14:59 UTC, SarahDonvito approved these changes, later dismissed

2024-12-04 10:06 UTC, AndreaCimini90 requested changes

2024-12-04 10:06 UTC, AndreaCimini90 commented on templates-assets/templates/NotificationAAR_RADDalt/index_it.html
> +          <div class="nine-px eleven-lh border-bottom mb-form" style="margin-bottom: 0;">
remove mb-form if margin bottom is 0

2024-12-04 17:05 UTC, AndreaCimini90 approved these changes

2024-12-04 17:06 UTC, merged